# Đảm bảo thiết lập phiên bản iOS
platform :ios, '14.0'

# Cấu hình để tắt theo dõi phân tích của CocoaPods
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Cấu hình project
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Xác định đường dẫn FLUTTER_ROOT
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# Đảm bảo cài đặt đúng với flutter pod helper
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Cài đặt flutter ios pods
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Cài đặt tất cả các pod cho Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# post_install cấu hình thêm cho geolocator và các pod khác
post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Cấu hình bổ sung cho các pods của Flutter
    flutter_additional_ios_build_settings(target)
    
    # Kiểm tra nếu target là geolocator_apple và bỏ qua quyền vị trí khi chạy nền
    if target.name == "geolocator_apple"
      target.build_configurations.each do |config|
        # Thêm macro để bỏ qua yêu cầu quyền truy cập vị trí luôn luôn
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'BYPASS_PERMISSION_LOCATION_ALWAYS=1']
      end
    end
  end
end

